OldaleTown_House1_MapScripts:: @ 81FBE85
	.byte 0

OldaleTown_House1_EventScript_1FBE86:: @ 81FBE86
	msgbox OldaleTown_House1_Text_1FBE8F, 2
	end

OldaleTown_House1_Text_1FBE8F: @ 81FBE8F
	.string "never use attract on a pokemon\n"
	.string "the same gender as yours.\p"
	.string "as it always fails\n"
	.string "the pokemon probably be like:\l"
	.string "“Miss me with that gay shit”\p"
	.string "or something like that.$"

