gUnknown_082C897B:: @ 82C897B
	.string "Herro! sorry about making tis game\p"
	.string "Wercome to POKéMON OOF VERSION!\p"
	.string "My name is BIRCH.\p"
	.string "But everyone carrs me PROF. WEEABOO\n"
	.string "because my caracter is tat Im a \p"
	.string "fucking weeb desu\n"
	.string "$"

gUnknown_082C89FB:: @ 82C89FB
	.string "Tis is wat we carr an “ELF”\p"
	.string "but some peopre call em “POKEMON”\p"
	.string "but you probabry knew tat arready\n"
	.string "wy else wourd you pray tis desu$"

gUnknown_082C8A1F:: @ 82C8A1F
	.string "arso tey injected cancerous normie\n"
	.string "memes into tis game so you better.\p"
	.string "watch out my nibba.\n"
	.string "...\l"
	.string "yes its terribre\p"
	.string "but we courd totarry discuss\n"
	.string "tis in te discord\p"
	.string "https://discord.gg/u8qDJGj\n"
	.string "its stirr being worked on\p"
	.string "as of 2/22/2018\n"
	.string "so maybe you courd help make\p"
	.string "tis pire of shit shittier?\n"
	.string "...\l"
	.string "That’s what wourd I do.\p"
	.string "$"

gUnknown_082C8BD0:: @ 82C8BD0
	.string "And you are?$"

gUnknown_082C8BDD:: @ 82C8BDD
	.string "Are you gay?\n"
	.string "Or do you like big goth tiddies?$"

gUnknown_082C8BFF:: @ 82C8BFF
	.string "haha yes\n"
	.string "\p"
	.string "Wat’s your name?$"

gUnknown_082C8C1C:: @ 82C8C1C
	.string "So it’s {PLAYER}-Kun?$"

gUnknown_082C8C2A:: @ 82C8C2A
	.string "haha tats a super gay name\n"
	.string "You’re {PLAYER}-Kun who’s moving to my\p"
	.string "hometown of RITTREROOT.\l"
	.string "I’m totarry shipping you with my child!\p"
	.string "$"

gUnknown_082C8C7A:: @ 82C8C7A
	.string "It doesnt matter what your name is\p"
	.string "because MAYxBRENDAN is the OTP\n"
	.string "oh wait\p"
	.string "we changed all the text so they are\n"
	.string "completely different characters now\l"
	.string "shit\p"
	.string "I just broke character too\n"
	.string "...\p"
	.string "just go to the elfs world already$"
